In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# cargar csv
df_avisos_aemet = pd.read_csv("avisos_aemet_2021_2026_moderate_severe_extreme.csv", encoding="latin-1")

In [3]:
df_avisos_aemet.head()

,ï»¿onset,expires,aÃ±o,mes,mes_num,estacion,event,severity,riesgo_numerico,duracion_horas,area_desc
0,2021-01-01 06:00:00+00:00,2021-01-01 19:59:59+00:00,2021,Enero,1,Invierno,Aviso de vientos de nivel amarillo,Moderate,1,13.999722,Valle del Almanzora y Los VÃ©lez
1,2021-01-01 06:00:00+00:00,2021-01-01 19:59:59+00:00,2021,Enero,1,Invierno,Moderate wind warning,Moderate,1,13.999722,Valle del Almanzora y Los VÃ©lez
2,2021-01-01 06:00:00+00:00,2021-01-01 19:59:59+00:00,2021,Enero,1,Invierno,Aviso de vientos de nivel amarillo,Moderate,1,13.999722,Nacimiento y Campo de Tabernas
3,2021-01-01 06:00:00+00:00,2021-01-01 19:59:59+00:00,2021,Enero,1,Invierno,Moderate wind warning,Moderate,1,13.999722,Nacimiento y Campo de Tabernas
4,2021-01-01 06:00:00+00:00,2021-01-01 20:59:59+00:00,2021,Enero,1,Invierno,Aviso de vientos de nivel amarillo,Moderate,1,14.999722,Poniente y AlmerÃ­a Capital

In [4]:
df_avisos_aemet.columns

Index(['ï»¿onset', 'expires', 'aÃ±o', 'mes', 'mes_num', 'estacion', 'event',
       'severity', 'riesgo_numerico', 'duracion_horas', 'area_desc'],
      dtype='object')

In [5]:
df_avisos_aemet.shape

(325806, 11)

In [6]:
df_avisos_aemet.tail()

,ï»¿onset,expires,aÃ±o,mes,mes_num,estacion,event,severity,riesgo_numerico,duracion_horas,area_desc
325801,2026-04-30 22:00:00+00:00,2026-05-01 06:59:59+00:00,2026,Abril,4,Primavera,Moderate thunderstorm warning,Moderate,1,8.999722,Altiplano de Murcia
325802,2026-04-30 22:02:33+00:00,2026-04-30 22:02:34+00:00,2026,Abril,4,Primavera,Aviso de lluvias de nivel amarillo,Moderate,1,0.000278,Noroeste de Murcia
325803,2026-04-30 22:02:33+00:00,2026-04-30 22:02:34+00:00,2026,Abril,4,Primavera,Moderate rain warning,Moderate,1,0.000278,Noroeste de Murcia
325804,2026-04-30 22:02:33+00:00,2026-04-30 22:02:34+00:00,2026,Abril,4,Primavera,Aviso de tormentas de nivel amarillo,Moderate,1,0.000278,Noroeste de Murcia
325805,2026-04-30 22:02:33+00:00,2026-04-30 22:02:34+00:00,2026,Abril,4,Primavera,Moderate thunderstorm warning,Moderate,1,0.000278,Noroeste de Murcia

In [7]:
df_avisos_aemet.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 325806 entries, 0 to 325805
Data columns (total 11 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   ï»¿onset         325806 non-null  object
 1   expires          325806 non-null  object
 2   aÃ±o             325806 non-null  int64
 3   mes              325806 non-null  object
 4   mes_num          325806 non-null  int64
 5   estacion         325806 non-null  object
 6   event            325806 non-null  object
 7   severity         325806 non-null  object
 8   riesgo_numerico  325806 non-null  int64
 9   duracion_horas   325806 non-null  float64
 10  area_desc        325806 non-null  object
dtypes: float64(1), int64(3), object(7)
memory usage: 27.3+ MB

In [8]:
df_avisos_aemet["event"].value_counts()

event
Moderate rain warning                  33943
Aviso de lluvias de nivel amarillo     33943
Aviso de costeros de nivel amarillo    26428
Moderate coastalevent warning          26428
Moderate thunderstorm warning          25049
                                       ...
Aviso de aludes de nivel naranja           5
Severe galerna warning                     4
Aviso de galernas de nivel naranja         4
Extreme galerna warning                    1
Aviso de galernas de nivel rojo            1
Name: count, Length: 62, dtype: int64